import { useTranslate } from '@Shared/translate.js';

const { setBulk } = useTranslate('ru');

setBulk({
    ru: {
        'form.required': 'Обязательное поле',
    },
});

setBulk({
    ru: {
        'auth.span.login': 'Авторизация',
        'auth.span.register': 'Регистрация',
        'auth.span.remember': 'Запомнить меня',
        'auth.span.invalid_credentials': 'Электронная почта или пароль указан неверно',
        'auth.span.invalid_email': 'Невалидная электронная почта',
        'auth.span.invalid_password_length': 'Пароль должен содержать более 6 символов',
        'auth.span.invalid_confirm_password': 'Пароль и пароль подтверждения не совпадают',
        'auth.span.user_already_exists': 'Пользователь с этим адресом электронной почты уже зарегистрирован',
        'auth.span.register.error': 'Что-то пошло не так, попробуйте еще раз',
        'auth.span.email': 'Электронная почта',
        'auth.span.password': 'Пароль',
        'auth.span.confirm': 'Подтвердите пароль',
        'auth.span.last_login': 'Последний вход',
        'auth.span.exit': 'Выйти',
        'auth.span.enter_to_game': 'Вход в игру',
        'auth.kick.sessionKey': 'Не разрешено проходить аутентификацию',
        'auth.kick.alreadyLoggedIn': 'Уже вошел в систему',
    },
});

setBulk({
    ru: {
        'character.select.no.account': 'Аккаунт не найден, перезапустите игру',
        'character.select.bad.write': 'Не удалось обновить, переподключитесь к серверу',
        'character.select.bad.character': 'Персонаж не существует, переподключитесь к серверу',
        'character.select.first.invalid': 'Недопустимое имя',
        'character.select.last.invalid': 'Недопустимая фамилия',
        'character.select.invalid.characters': 'Имя содержит недопустимые символы',
        'character.select.username.taken': 'Имя недоступно',
        'character.select.character.not.found': 'Персонаж не найден, обновите персонажи',
        'character.select.submit': 'Отправить',
        'character.select.cancel': 'Отменить',
        'character.select.confirm': 'Подтвердить',
        'character.select.delete': 'Удалить',
        'character.select.create': 'Создать персонажа',
        'character.select.no.appearance': 'Нет внешности',
        'character.select.confirm.delete': 'Вы уверены, что хотите удалить?',
        'character.select.first': 'Имя / Первое имя',
        'character.select.last': 'Фамилия',
        'character.select.max.characters.reached': 'Достигнуто максимальное количество персонажей',
    },
});

setBulk({
    ru: {
        'character.creator.unable.to.save': 'Не удалось сохранить персонажа, переподключитесь к серверу',
        'character.creator.blemishes': 'Недостатки',
        'character.creator.visibility': 'Видимость',
        'character.creator.sun.damage': 'Повреждения от солнца',
        'character.creator.damage': 'Повреждения',
        'character.creator.freckles': 'Веснушки',
        'character.creator.aging': 'Старение',
        'character.creator.lipstick': 'Помада',
        'character.creator.color': 'Цвет',
        'character.creator.blusher': 'Румяна',
        'character.creator.makeup': 'Макияж',
        'character.creator.blemish': 'Пятно',
        'character.creator.face.father': 'Лицо отца',
        'character.creator.face.mother': 'Лицо матери',
        'character.creator.skin.father': 'Кожа отца',
        'character.creator.skin.mother': 'Кожа матери',
        'character.creator.skin.mix': 'Смешивание кожи',
        'character.creator.face.mix': 'Смешивание лиц',
        'character.creator.eyes': 'Глаза',
        'character.creator.body.type': 'Тип тела',
        'character.creator.save': 'Сохранить',
        'character.creator.processing': 'Обработка...',
        'character.creator.hair': 'Волосы',
        'character.creator.hair.color': 'Цвет волос',
        'character.creator.hair.highlight': 'Выделение волос',
        'character.creator.eyebrows': 'Брови',
        'character.creator.eyebrows.color': 'Цвет бровей',
        'character.creator.facial.hair': 'Лицевые волосы',
        'character.creator.facial.color': 'Цвет лицевых волос',
        'character.creator.category': 'Категория',
        'character.creator.nose.width': 'Ширина носа',
        'character.creator.nose.height': 'Высота носа',
        'character.creator.nose.length': 'Длина носа',
        'character.creator.nose.profile': 'Профиль носа',
        'character.creator.nose.tip': 'Кончик носа',
        'character.creator.nose.broke': 'Сломанный нос',
        'character.creator.brow.height': 'Высота бровей',
        'character.creator.brow.depth': 'Глубина бровей',
        'character.creator.cheek.height': 'Высота щек',
        'character.creator.cheek.depth': 'Глубина щек',
        'character.creator.cheek.puffed': 'Надутые щеки',
        'character.creator.eyes.size': 'Размер глаз',
        'character.creator.lips.size': 'Размер губ',
        'character.creator.jaw.width': 'Ширина челюсти',
        'character.creator.jaw.rounded': 'Закругленная челюсть',
        'character.creator.chin.height': 'Высота подбородка',
        'character.creator.chin.depth': 'Глубина подбородка',
        'character.creator.chin.pointed': 'Заостренный подбородок',
        'character.creator.chin.dimple': 'Ямочка на подбородке',
        'character.creator.neck.size': 'Размер шеи',
    },
});
